#!/bin/bash
# Patch the generated index.tsx with custom exports to resolve naming conflicts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Check if src/index.tsx exists
if [ ! -f "$PROJECT_ROOT/src/index.tsx" ]; then
  echo "❌ src/index.tsx not found. Run ubrn generate first."
  exit 1
fi

echo "✅ Patching src/index.tsx with custom exports..."

# Copy the exports template from kashir.tsx but use relative paths
# This embeds the exports directly into src/index.tsx
cat > "$PROJECT_ROOT/src/index.tsx" << 'PATCH_EOF'
// Generated by uniffi-bindgen-react-native
import installer from './NativeKashir';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings with resolved naming conflicts
// Re-export Nostr SDK types with explicit renames for conflicting names
export {
  Keys as NostrKeys,
  PublicKey as NostrPublicKey,
  SecretKey as NostrSecretKey,
} from './generated/nostr_sdk';

// Re-export all other Nostr SDK exports
export type {
  AdmitPolicy,
  ArticlesCuration,
  Bookmarks,
  ClientBuilderInterface,
  ClientInterface,
  ClientMessageEnum,
  ClientMessageInterface,
  ConnectionInterface,
  ConnectionMode,
  Contact,
  CoordinateInterface,
  CustomNostrSigner,
  CustomWebSocketTransport,
  EmojiInfo,
  Emojis,
  EncryptedSecretKeyInterface,
  EventBuilderInterface,
  EventDeletionRequest,
  EventIdInterface,
  EventInterface,
  EventsInterface,
  ExternalContentId,
  ExtractedComment,
  FeeSchedule,
  FeeSchedules,
  FileMetadataInterface,
  FilterInterface,
  FilterRecord,
  GenericTag,
  GetBalanceResponse,
  GetInfoResponse,
  GitIssue,
  GitPatch,
  GitPatchCommitter,
  GitPatchContent,
  GitRepositoryAnnouncement,
  HandleNotification,
  HttpData,
  Identity,
  Image,
  ImageDimensions,
  Interests,
  JobFeedbackDataInterface,
  JsonValue,
  KeysendTlvRecord,
  KeysInterface,
  KindInterface,
  Limitation,
  ListTransactionsRequest,
  LiveEvent,
  LiveEventHost,
  LiveEventStatus,
  LookupInvoiceRequest,
  LookupInvoiceResponse,
  MakeInvoiceRequest,
  MakeInvoiceResponse,
  MetadataInterface,
  MetadataRecord,
  MultiPayInvoiceRequest,
  MultiPayKeysendRequest,
  MuteList,
  NegentropyItem,
  Nip05ProfileInterface,
  Nip19CoordinateInterface,
  Nip19Enum,
  Nip19EventInterface,
  Nip19Interface,
  Nip19ProfileInterface,
  Nip21Enum,
  Nip21Interface,
  Nip46Request,
  Nip47Error,
  NostrConnectInterface,
  NostrConnectMessage,
  NostrConnectMetadataInterface,
  NostrConnectUriInterface,
  NostrDatabaseInterface,
  NostrSdkError,
  NostrSignerInterface,
  NostrWalletConnectOptionsInterface,
  NostrWalletConnectUriInterface,
  NwcInterface,
  OptionsInterface,
  Output,
  PayInvoiceRequest,
  PayInvoiceResponse,
  PayKeysendRequest,
  PayKeysendResponse,
  Person,
  ProductData,
  Protocol,
  PublicKeyInterface,
  Reconciliation,
  ReconciliationOutput,
  ReconciliationSendFailureItem,
  RelayConnectionStatsInterface,
  RelayInformationDocumentInterface,
  RelayInterface,
  RelayLimitsInterface,
  RelayMessageEnum,
  RelayMessageInterface,
  RelayOptionsInterface,
  ReqExitPolicy,
  RequestInterface,
  RequestParams,
  ResponseInterface,
  ResponseResult,
  Retention,
  RetentionKind,
  SaveEventStatus,
  SecretKeyInterface,
  SendEventOutput,
  ServerConfigInterface,
  ShippingCost,
  ShippingMethodInterface,
  ShippingMethodRecord,
  SignerBackend,
  SingleLetterTagInterface,
  StallDataInterface,
  StallDataRecord,
  SubscribeAutoCloseOptionsInterface,
  SubscribeOptionsInterface,
  SubscribeOutput,
  SyncOptionsInterface,
  TagClientAddress,
  TagInterface,
  TagKind,
  TagStandard,
  TagsInterface,
  TimestampInterface,
  UnsignedEventInterface,
  UnwrappedGiftInterface,
  WebSocketAdapter,
  WebSocketAdapterWrapperInterface,
  WebSocketCloseFrame,
  WebSocketMessage,
  ZapRequestDataInterface,
} from './generated/nostr_sdk';

export {
  AdmitPolicyImpl,
  AdmitStatus,
  Alphabet,
  Client,
  ClientBuilder,
  ClientMessage,
  ClientMessageEnum_Tags,
  Connection,
  ConnectionMode_Tags,
  ConnectionTarget,
  Coordinate,
  CustomNostrSignerImpl,
  CustomWebSocketTransportImpl,
  DataVendingMachineStatus,
  EncryptedSecretKey,
  EncryptedSecretKeyVersion,
  ErrorCode,
  Event,
  EventBuilder,
  EventId,
  Events,
  ExternalContentId_Tags,
  ExternalIdentity,
  ExtractedComment_Tags,
  FileMetadata,
  Filter,
  GitPatchContent_Tags,
  HandleNotificationImpl,
  HttpMethod,
  JobFeedbackData,
  JsonValue_Tags,
  KeySecurity,
  Kind,
  KindStandard,
  LiveEventMarker,
  LiveEventStatus_Tags,
  LogLevel,
  Marker,
  Metadata,
  Method,
  Nip05Profile,
  Nip19,
  Nip19Coordinate,
  Nip19Enum_Tags,
  Nip19Event,
  Nip19Profile,
  Nip21,
  Nip21Enum_Tags,
  Nip44Version,
  Nip46Request_Tags,
  NostrConnect,
  NostrConnectMessage_Tags,
  NostrConnectMetadata,
  NostrConnectUri,
  NostrDatabase,
  NostrSdkError_Tags,
  NostrSigner,
  NostrWalletConnectOptions,
  NostrWalletConnectUri,
  Nwc,
  Options,
  Protocol_Tags,
  RejectedReason,
  Relay,
  RelayConnectionStats,
  RelayInformationDocument,
  RelayLimits,
  RelayMessage,
  RelayMessageEnum_Tags,
  RelayMetadata,
  RelayOptions,
  RelayStatus,
  Report,
  ReqExitPolicy_Tags,
  Request,
  RequestParams_Tags,
  Response,
  ResponseResult_Tags,
  RetentionKind_Tags,
  SaveEventStatus_Tags,
  ServerConfig,
  ShippingMethod,
  SignerBackend_Tags,
  SingleLetterTag,
  StallData,
  SubscribeAutoCloseOptions,
  SubscribeOptions,
  SyncDirection,
  SyncOptions,
  Tag,
  TagKind_Tags,
  TagStandard_Tags,
  Tags,
  Timestamp,
  TransactionType,
  UnsignedEvent,
  UnwrappedGift,
  WebSocketAdapterImpl,
  WebSocketAdapterWrapper,
  WebSocketMessage_Tags,
  ZapRequestData,
  ZapType,
  createDelegationTag,
  decryptReceivedPrivateZapMessage,
  decryptSentPrivateZapMessage,
  extractRelayList,
  generateSharedKey,
  getLeadingZeroBits,
  getPrefixesForDifficulty,
  giftWrapFromSeal,
  gitHashVersion,
  initLogger,
  nip04Decrypt,
  nip04Encrypt,
  nip21ExtractFromText,
  nip44Decrypt,
  nip44Encrypt,
  nip57AnonymousZapRequest,
  nip57PrivateZapRequest,
  signDelegation,
  tagKindToString,
  validateDelegationTag,
  verifyDelegationSignature,
} from './generated/nostr_sdk';

// Re-export everything from CDK (using wildcard since conflicts are resolved)
export * from './generated/cdk_ffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as nostr_sdk from './generated/nostr_sdk';
import * as cdk_ffi from './generated/cdk_ffi';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  nostr_sdk.default.initialize();
  cdk_ffi.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
  nostr_sdk,
  cdk_ffi,
};
PATCH_EOF

echo "✅ Successfully patched src/index.tsx"
