#!/bin/bash
# Patch the generated index.tsx with custom exports to resolve naming conflicts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Check if src/index.tsx exists
if [ ! -f "$PROJECT_ROOT/src/index.tsx" ]; then
  echo "❌ src/index.tsx not found. Run ubrn generate first."
  exit 1
fi

echo "✅ Patching src/index.tsx with custom exports..."

# Copy the exports template from kashir.tsx but use relative paths
# This embeds the exports directly into src/index.tsx
cat > "$PROJECT_ROOT/src/index.tsx" << 'PATCH_EOF'
// Generated by uniffi-bindgen-react-native
import installer from './NativeKashir';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Resolve the 3 names that conflict between nostr_sdk and cdk_ffi.
// Explicit exports take precedence over export *, so the wildcards below
// will skip these names automatically.
export { Keys, PublicKey, SecretKey } from './generated/cdk_ffi';
export {
  Keys as NostrKeys,
  PublicKey as NostrPublicKey,
  SecretKey as NostrSecretKey,
} from './generated/nostr_sdk';

// Re-export everything else from both modules
export * from './generated/nostr_sdk';
export * from './generated/cdk_ffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as nostr_sdk from './generated/nostr_sdk';
import * as cdk_ffi from './generated/cdk_ffi';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  nostr_sdk.default.initialize();
  cdk_ffi.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
  nostr_sdk,
  cdk_ffi,
};
PATCH_EOF

echo "✅ Successfully patched src/index.tsx"
