import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  // Login Screen Styles
  loginSafeArea: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#1a1a1a',
  },
  loginTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: '#fff',
  },
  loginSubtitle: {
    fontSize: 16,
    color: '#ccc',
    marginBottom: 30,
    textAlign: 'center',
    lineHeight: 22,
  },
  loginHint: {
    fontSize: 12,
    color: '#999',
    marginTop: 20,
    textAlign: 'center',
    lineHeight: 18,
  },
  // Login Method Toggle Styles
  loginMethodContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 4,
  },
  loginMethodButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  activeLoginMethod: {
    backgroundColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  loginMethodText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#999',
  },
  activeLoginMethodText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  warningText: {
    fontSize: 12,
    color: '#ff9500',
    marginBottom: 15,
    textAlign: 'center',
    lineHeight: 16,
  },
  // Amber Login Styles
  amberContainer: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#444',
  },
  amberDescription: {
    fontSize: 14,
    color: '#fff',
    marginBottom: 8,
    textAlign: 'center',
    lineHeight: 20,
  },
  amberNote: {
    fontSize: 12,
    color: '#ccc',
    textAlign: 'center',
    lineHeight: 16,
  },
  // Header Styles
  headerContainer: {
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 5,
    backgroundColor: '#2a2a2a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  headerTop: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 0,
  },
  userActions: {
    alignItems: 'center',
    marginBottom: 10,
  },
  headerButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    gap: 10,
  },
  inputContainer: {
    padding: 20,
    backgroundColor: '#2a2a2a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
    color: '#fff',
  },
  subtitle: {
    fontSize: 14,
    color: '#ccc',
    marginBottom: 15,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: '#1a1a1a',
    color: '#fff',
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#ccc',
  },
  postsContainer: {
    flex: 1,
  },
  postCount: {
    padding: 15,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  postCard: {
    backgroundColor: '#2a2a2a',
    padding: 15,
    marginHorizontal: 10,
    marginVertical: 5,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  postDate: {
    fontSize: 12,
    color: '#999',
    marginBottom: 8,
  },
  postContent: {
    fontSize: 16,
    lineHeight: 22,
    color: '#fff',
  },
  separator: {
    height: 1,
    backgroundColor: '#444',
    marginTop: 15,
  },
  // Tab Navigation Styles
  tabContainer: {
    flexDirection: 'row',
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  activeTab: {
    backgroundColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#999',
  },
  activeTabText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  postAuthor: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#81b0ff',
    marginBottom: 4,
  },
  // Floating Action Button Styles
  fab: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabText: {
    fontSize: 24,
    color: '#fff',
    fontWeight: 'bold',
  },
  // Compose Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  modalContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2a2a2a',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  closeButton: {
    padding: 5,
  },
  closeButtonText: {
    fontSize: 18,
    color: '#999',
  },
  composeInput: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#1a1a1a',
    color: '#fff',
    minHeight: 120,
    textAlignVertical: 'top',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
    gap: 10,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#444',
  },
  postButton: {
    backgroundColor: '#007AFF',
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#fff',
  },
  characterCount: {
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
    marginTop: 8,
  },
  // Back button style
  backButton: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '500',
  },
  // Post action styles
  postActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#444',
    paddingHorizontal: 4,
  },
  actionButton: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 6,
    backgroundColor: '#333',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 1,
  },
  actionButtonText: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '500',
    textAlign: 'center',
  },
  // Additional layout styles
  fullContainer: {
    flex: 1,
  },
  tabContent: {
    flex: 1,
    display: 'flex',
  },
  hiddenTabContent: {
    flex: 1,
    display: 'none',
  },
  // Button state styles
  disabledButton: {
    opacity: 0.5,
  },
  enabledButton: {
    opacity: 1,
  },
  // Event Modal Form Styles
  eventModalContainer: {
    maxHeight: '90%',
  },
  eventModalContent: {
    maxHeight: 400,
    paddingVertical: 10,
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#1a1a1a',
    color: '#fff',
  },
  formTextArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  formDateButton: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#1a1a1a',
  },
  formDateText: {
    fontSize: 16,
    color: '#fff',
  },
  formToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // Event modal specific styles
  formTimeButton: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#1a1a1a',
    marginTop: 8,
  },
  quickSelectRow: {
    flexDirection: 'row',
    marginTop: 8,
    gap: 8,
  },
  quickSelectButton: {
    flex: 1,
    backgroundColor: '#444',
  },
  endDateQuickSelectRow: {
    flexDirection: 'row',
    marginTop: 8,
  },
  // Additional modal styles
  modalContent: {
    flex: 1,
    paddingVertical: 10,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 10,
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseText: {
    fontSize: 18,
    color: '#999',
    fontWeight: 'bold',
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  button: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimary: {
    backgroundColor: '#81b0ff',
  },
  buttonSecondary: {
    backgroundColor: '#444',
  },
  buttonPrimaryText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },
  buttonSecondaryText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  imagePreviewContainer: {
    marginTop: 12,
    alignItems: 'center',
  },
  imagePreview: {
    width: 100,
    height: 100,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  imageErrorText: {
    color: '#ff6b66',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  // Post image styles
  imageContainerSingle: {
    width: '100%',
    alignItems: 'center',
  },
  imageContainerDouble: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  imageContainerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  imageWrapper: {
    position: 'relative',
    borderRadius: 8,
    overflow: 'hidden',
  },
  lastImageWrapper: {
    position: 'relative',
  },
  postImage: {
    borderRadius: 8,
  },
  imageLarge: {
    width: '100%',
    height: 200,
  },
  imageMedium: {
    width: '48%',
    height: 120,
  },
  imageSmall: {
    width: '48%',
    height: 100,
  },
  imageError: {
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  imageErrorTextSmall: {
    color: '#999',
    fontSize: 10,
    marginTop: 2,
    textAlign: 'center',
  },
  moreImagesOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  moreImagesText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  moreImagesIndicator: {
    color: '#999',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
  },
  // Event selection styles
  eventSelectionSubtext: {
    color: '#999',
    fontSize: 14,
    marginBottom: 12,
    fontStyle: 'italic',
  },
  eventsList: {
    maxHeight: 200,
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    backgroundColor: '#1a1a1a',
  },
  eventItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  eventItemSelected: {
    backgroundColor: '#2a3a4a',
  },
  eventItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#81b0ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  eventCheckboxText: {
    color: '#81b0ff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  eventDetails: {
    flex: 1,
  },
  eventTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 2,
  },
  eventDate: {
    color: '#999',
    fontSize: 12,
  },
  eventsLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  eventsLoadingText: {
    color: '#999',
    fontSize: 14,
    marginLeft: 8,
  },
  moreEventsIndicator: {
    padding: 12,
    alignItems: 'center',
    backgroundColor: '#333',
  },
  moreEventsText: {
    color: '#999',
    fontSize: 12,
    fontStyle: 'italic',
  },
  // Post Detail Screen Styles
  originalPost: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#444',
    paddingBottom: 20,
  },
  repliesSection: {
    flex: 1,
  },
  repliesHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  replyContainer: {
    marginLeft: 20,
    borderLeftWidth: 2,
    borderLeftColor: '#444',
    paddingLeft: 15,
    marginBottom: 10,
  },
  noRepliesText: {
    color: '#999',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
  },
  noRepliesContainer: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  noRepliesSubtext: {
    color: '#666',
    textAlign: 'center',
    fontSize: 14,
    marginTop: 8,
    fontStyle: 'italic',
  },
  // Image Modal Styles
  imageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
  },
  imageModalContainer: {
    flex: 1,
  },
  imageModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    position: 'absolute',
    top: 50, // Adjust for SafeAreaView
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  imageModalCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageModalCloseText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  imageModalCounter: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  imageModalContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageModalImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  imageModalImage: {
    width: '100%',
    height: '100%',
    minWidth: 200,
    minHeight: 200,
  },
  imageModalError: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 200,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
  },
  imageModalErrorIcon: {
    fontSize: 48,
    marginBottom: 10,
  },
  imageModalErrorText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  imageModalNavButton: {
    position: 'absolute',
    top: '50%',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
  },
  imageModalPrevButton: {
    left: 20,
  },
  imageModalNextButton: {
    right: 20,
  },
  imageModalNavText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
  },
  imageModalThumbnails: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    height: 80,
  },
  imageModalThumbnailsContainer: {
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  imageModalThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginHorizontal: 5,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  imageModalThumbnailActive: {
    borderColor: '#81b0ff',
  },
  imageModalThumbnailImage: {
    width: '100%',
    height: '100%',
  },
});
