name: Build (Release)
on:
  workflow_dispatch:

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: android
          release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-libs
          path: android/**/*.a
          if-no-files-found: error

  ios:
    name: iOS
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: ios
          release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework
          path: build/*.xcframework
          if-no-files-found: error
